--
-- Officers
--
-- NOTE: PostgreSQL 13 or above is required (for the gen_random_uuid() function)
--
CREATE TABLE IF NOT EXISTS officer (
    officer_id    BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START 2000 INCREMENT 1),
    uuid          UUID        NOT NULL DEFAULT gen_random_uuid(),
    created       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    first_name    TEXT        NOT NULL,
    last_name     TEXT        NOT NULL,
    email_address TEXT        NOT NULL UNIQUE,
    password_hash TEXT        NOT NULL
);

CREATE INDEX ON officer (created);
CREATE INDEX ON officer (first_name);
CREATE INDEX ON officer (last_name);

INSERT INTO officer (uuid, first_name, last_name, email_address, password_hash)
VALUES ('34e45a34-3aa6-4fd0-ac4a-7581e1ad3a11', 'Will', 'Riker', 'riker@starship-enterprise.outer.space', '$argon2id$v=19$m=4096,t=300,p=2$MTY3MTQ1NjcwNQ$uIIph3QFDiMAILBCm+k29bhdvLn6w+srx9Bk+8w9Aic');
